---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[vsearch::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
