sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-trusty to install the stable release
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  global:
    # Ignore warnings when running specs.
    - RUBYOPT="-W0"
  matrix:
    - CHEF_VERSION=current INSTANCE=default-ubuntu-1404
    - CHEF_VERSION=current INSTANCE=default-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef gem install kitchen-docker
  - /opt/chefdk/bin/chef exec rake tests

script:
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

notifications:
  slack:
    rooms:
      secure: KZW2IXMXSPTCkIqcuRH3dEllcsAg88+fXeYsWjyKkfaOOk94mCYArcpHxPoMciE6tmOE+5aywLwnyoS1LedMgkdbHnCA4XmPfoofcPcKTC7vqVzygaD3B6lFvIebUXGUCdnPzsqzwAV+eKtrowuvNqOVGNzpaz811z+Yn9p+xQ7ijSHwXtBspdKS8kHWJv0CqPQMm88+hoIsRlDHHhVgxswTvqzipGNzO2AOgHVDAYuFU1fEw6NhhfNSNplhvm2OhZ2iARvhMXg2NaNIx0XHiV3axi++SDi5Oss5KmYBCKQPBuUqmrbnPjC3OrbAJGu88zqQDaQAU/bDGtQihfFG6gdpDM+7Vw+2mHShwRWG68aE6yVuiVK+IwqYHykNAqKDpvgGVr4QFZt8FDPX/FGAFl88Qi8SNPtkiQ8wqKVb6oGM54gxhHHAAfotHUZn4T+Eo4Flp3YlhfIZlwGGYXSw4ve+96WGYshNY+VPIulV9z+uEiqdstf/dwjgbyCiHPSH7EDKkchuz3l/XvsZKhH53G/5oDIGsfMDigJNzu0UJj/osdhrmwXzZpw2NGXhFe0ce4pdcqW50/ijJMsdWV9LohUYBXZ3iuyIkIdwbM/vThDpD5Q9cuc+FxOzftnAWbGoSsAjWU122RSaeQC2+T1aXOgCiqmralGsHF+YXZTqUMk=
