sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  global:
  - RUBYOPT="-W0"
  - secure: KoPqY52lOYzfmTMS1K01FKajOhZJThdrdNUnAPTE/HOb49OevQggyPQCijoQXfbYh/NHymqGlSlhIEL2Ai4nGZSLwwwn16ws6j08ssh03kACKYTUWLeKeoe3ySQTQRtcxx1MrLLDOtT80jwEk7o4FE/wKjI5WZKFGV4Swo6n1CFLX1HmiN3a1S8tRu8RKhhGZk2JHzKqY9BK6Hbl5cCylYbsVLItLAX4ylYxRlldfG1WAEALyteTYuxmycDzV4g4zkMN2lB2xTj5rj/plS1RsJ7n4crq32Jl23goQQih48snYgByGev6bygh6qrV+czGl4dPqc3t9APHjyinid6FNKj9MmM4flmprwK+2bRYMO5Xoxm7JdKSqT/kmRO9qpATG3xZcOlYOKYI6+Un8q0dab/UpMJR/5p2XEq6Qg8Zj6e/VBXOj7rB6OTuonBcSWYsIgC/T/4VZHUMNDavIHo1qFV1JEKVEMktHeerlwX54MBS8d6M5PadohZNN9OWHQY+1+nWyZoE686Nt+eotuVggE4gzg7gZsJ7HoFQ9VumBg+hPIwkkkJmIivtE/5WrMLmOpH8LLxJborxU0JjATPUn4Cw236QU1q9ogzC636UhVs5KMzU9LtTqD9F0DvJzIhI0zP3KwiovMJvNhRi3GT27IXKYcGa2kPw7iPqFAwO5h8=
  matrix:
  - CHEF_VERSION=current INSTANCE=default-centos-7
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-docker
- chef gem install travis
- "/opt/chefdk/bin/chef exec rake tests"
script:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
- chmod +x trigger_dependent_build.sh
- ./trigger_dependent_build.sh $TRAVIS_ACCESS_TOKEN

notifications:
  slack:
    secure: FudhlsDwP/+EsLY7CkX7P3317rJaE4SoUxVElr35KkPHhyYe/oT4yMJXYWzse6pwE8xN02O60yTxeCEltSoYabrfxocsP/A2a1P96Jx60n/Axm3TWJ9J1Wh8+y0P1dSo1yxj0DqbvWOeAYoGMtrt+YvxWMbsq3kEsgw5hzCX0dEokAz6DNKbPirfynEupbnARWpnaFWpU7293QGV4M8PZiltidH33dJrS26hAUtehlKwoDZlU8bxYKAABg2PAGNGcHATUnaaJQ8p24bbZwQzB7Y0OoSeU4fD4Oc1KtVfEbC7LkT7IubZ85vz+ZAVay4R7mh6QzqjOkZiI/iEFc3++JP9FsY9Xk2bgX3zIFFYGP+s5HfZx2c4ko6CytrmHKFajqoHMepiKwtcqz5Plr6DBSPEPpjjlOlLK42S8QZA/pUwrAP7FevC7PCBuplX80DPueNccf+diNAj6Yw/0veyXm8XYx2VwwjPRCTzshBvR/XYDU2s5p/RcWUTuxeYYnzTXqdAGoYI/vNmbcvHScNLdBy/K8fxNwlYntvr4DXf10qD1X4EOWe62rwle+AlzL9y2HF/3A55IlA4k6tu+J1pgNzeAdAvb86tnvmV6aPpKqgOXopOP/Cgy/aby21baJdTbYMYi9Qcsza/8/ziReXhvZpmIMrLiG8HVLnhwGUeNMc=
    on_failure: change
    on_success: change
  email:
    on_success: change
    on_failure: always
