sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  global:
  - secure: HRF1VB916GmhYNicqioMWCOuwecMbyb8Ny20bDckC5d5WNh0ZqQplyzjuS/7e79dcHb0K/SKtruSvT6DRuc7qwBIjkrkVE2oz5KqCVKbiV+BPM5dUfeW8G+ay37yYNwMk6y+VCPB6x/CT3HpyuX13AAeNhaVuWn7G/qDfzft0BXr6E2hDGAhHUL3CbTjABdBK1zDbIpONbsxrhZRXqFYOAu4tN/3FHi9gAk9OHj/3u2vKPaRF8qJ6tCKL8/rWKbYBNgSkQkmSi/VgamFSVfsDZK+PAC7mNAXW0ITDfg2m4svDzRX/qOD5Bubhkfu5d5MC5ZRJpU9i/G8vATK59BkztNeySgTIzbGQ+EMvNmL/j74QBM5LzWtZdL5H6A0dABd0e+ywLs6sCyH3vmCUj81SUfUrg0aLWpDjjYbkNDDT4ZRFvqYhQ/aM2eJOgEjO0k1chbVCqCh4mkhl8By1qL+icF0p3cZ3pDowyVbmGvuR6nSTndLCUzw4EwdEEPTNvt7HB58B6G5p9pW4VqmuI1QlDllIuJi1/kLE1b7nSEyW6p7atkZIVnSP8tY3Ioa0bhrvRcIw+bkmY4rll7eZYvQ1mDgIWcLtxRyfbjgKzvqc3BsAIRvHWl0142vZau2hByfRjSZz6MG1+mPB1Rykff2GygPIdKwIxyO/1A3UIwPS2Q=
  matrix:
  - CHEF_VERSION=current INSTANCE=default-centos-7
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1404
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-docker
- "/opt/chefdk/bin/chef exec rake tests"
script:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
after_script:
- chmod +x trigger_dependent_build.sh
- "./trigger_dependent_build.sh EagleGenomics-cookbooks vsearch_runnable private $TRAVIS_ACCESS_TOKEN"
notifications:
  slack:
    secure: FudhlsDwP/+EsLY7CkX7P3317rJaE4SoUxVElr35KkPHhyYe/oT4yMJXYWzse6pwE8xN02O60yTxeCEltSoYabrfxocsP/A2a1P96Jx60n/Axm3TWJ9J1Wh8+y0P1dSo1yxj0DqbvWOeAYoGMtrt+YvxWMbsq3kEsgw5hzCX0dEokAz6DNKbPirfynEupbnARWpnaFWpU7293QGV4M8PZiltidH33dJrS26hAUtehlKwoDZlU8bxYKAABg2PAGNGcHATUnaaJQ8p24bbZwQzB7Y0OoSeU4fD4Oc1KtVfEbC7LkT7IubZ85vz+ZAVay4R7mh6QzqjOkZiI/iEFc3++JP9FsY9Xk2bgX3zIFFYGP+s5HfZx2c4ko6CytrmHKFajqoHMepiKwtcqz5Plr6DBSPEPpjjlOlLK42S8QZA/pUwrAP7FevC7PCBuplX80DPueNccf+diNAj6Yw/0veyXm8XYx2VwwjPRCTzshBvR/XYDU2s5p/RcWUTuxeYYnzTXqdAGoYI/vNmbcvHScNLdBy/K8fxNwlYntvr4DXf10qD1X4EOWe62rwle+AlzL9y2HF/3A55IlA4k6tu+J1pgNzeAdAvb86tnvmV6aPpKqgOXopOP/Cgy/aby21baJdTbYMYi9Qcsza/8/ziReXhvZpmIMrLiG8HVLnhwGUeNMc=
    on_failure: change
    on_success: change
  email:
    on_success: change
    on_failure: always
