sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  global:
  - RUBYOPT="-W0"
  - secure: AvVk3IKYMzgUfOJUemFCzUapu4S9h4mNJnkM0maRnCJ2Fe7Gp88b1gm0rbkXlIhba4ly/2t1ix0ArmHM+hil0KprEhZRkzzfmVaIwcRdgKvKBEJsEQez/Avppvan32VB1S6nmES/sX6qnbTVtDfKLHo04I08VMIg7yaV97slQXZUyXYLquY8/9u6zQxPZ7kgR/3f/5EoKxzG1kGktheJ3BtfSQfBvG6vkIc0nc04dOqrI3uv4R4Ui3T3ji9G0X0noFG3cQu9G85o25rfShvV3OY/Wub6McWdK6/5f+JZqRm3BL2AMEG/QfHU1vcZK77Vms1mrCtEJhF1qEF6t4Adgay6lU8i7gYJyYXvBVblQTukvGFjnvDQR6Aaz4EZ+lBBQQH2YJbXiH+KG/J2dV4a4Gyrm1LVTx+Cu+xqNcnBQDdaC+SQv6D1KirCHqvWSMnunjBSk/jwZwFyI3DRW8ics2SvJ7F/tKHaGTuzbfMCr9zUiKLhusypp36TS914lAWv1iS9EoIBZUHHEb0bvFl59a7ljNpJV18P+oiRuwpt7TtP9+Sc/ZbLJkzeQDekDfzrh7IssYA3WX33YsaGsO9oQn/0SsZ3S7Ky142EUV9zJyQBVbnNeTt0c4afbkckAXjYmKCmE7/uXQKu/PWwaEKnAk5AVvUlFMa/Ttr8qup2sjo=
  matrix:
  - CHEF_VERSION=current INSTANCE=default-centos-7
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-docker
- chef gem install travis
- "/opt/chefdk/bin/chef exec rake tests"
script:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
after-script:
- chmod +x trigger_dependent_build.sh
- "./trigger_dependent_build.sh $TRAVIS_ACCESS_TOKEN"
notifications:
  slack:
    secure: FudhlsDwP/+EsLY7CkX7P3317rJaE4SoUxVElr35KkPHhyYe/oT4yMJXYWzse6pwE8xN02O60yTxeCEltSoYabrfxocsP/A2a1P96Jx60n/Axm3TWJ9J1Wh8+y0P1dSo1yxj0DqbvWOeAYoGMtrt+YvxWMbsq3kEsgw5hzCX0dEokAz6DNKbPirfynEupbnARWpnaFWpU7293QGV4M8PZiltidH33dJrS26hAUtehlKwoDZlU8bxYKAABg2PAGNGcHATUnaaJQ8p24bbZwQzB7Y0OoSeU4fD4Oc1KtVfEbC7LkT7IubZ85vz+ZAVay4R7mh6QzqjOkZiI/iEFc3++JP9FsY9Xk2bgX3zIFFYGP+s5HfZx2c4ko6CytrmHKFajqoHMepiKwtcqz5Plr6DBSPEPpjjlOlLK42S8QZA/pUwrAP7FevC7PCBuplX80DPueNccf+diNAj6Yw/0veyXm8XYx2VwwjPRCTzshBvR/XYDU2s5p/RcWUTuxeYYnzTXqdAGoYI/vNmbcvHScNLdBy/K8fxNwlYntvr4DXf10qD1X4EOWe62rwle+AlzL9y2HF/3A55IlA4k6tu+J1pgNzeAdAvb86tnvmV6aPpKqgOXopOP/Cgy/aby21baJdTbYMYi9Qcsza/8/ziReXhvZpmIMrLiG8HVLnhwGUeNMc=
    on_failure: change
    on_success: change
  email:
    on_success: change
    on_failure: always
